apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redline-api

resources:
  - namespace.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app: redline-api
  managed-by: kustomize
